export interface Neighborhood {
  slug: string;
  name: string;
}

export const SAO_PAULO_NEIGHBORHOODS: Neighborhood[] = [
  { slug: 'aclimacao', name: 'Aclimação' },
  { slug: 'agua-branca', name: 'Água Branca' },
  { slug: 'agua-fria', name: 'Água Fria' },
  { slug: 'alto-da-lapa', name: 'Alto da Lapa' },
  { slug: 'alto-de-pinheiros', name: 'Alto de Pinheiros' },
  { slug: 'barra-funda', name: 'Barra Funda' },
  { slug: 'bela-vista', name: 'Bela Vista' },
  { slug: 'belem', name: 'Belém' },
  { slug: 'bom-retiro', name: 'Bom Retiro' },
  { slug: 'brooklin', name: 'Brooklin' },
  { slug: 'cambuci', name: 'Cambuci' },
  { slug: 'campo-belo', name: 'Campo Belo' },
  { slug: 'casa-verde', name: 'Casa Verde' },
  { slug: 'centro', name: 'Centro' },
  { slug: 'chacara-inglesa', name: 'Chácara Inglesa' },
  { slug: 'chacara-santo-antonio', name: 'Chácara Santo Antônio' },
  { slug: 'cidade-sao-francisco', name: 'Cidade São Francisco' },
  { slug: 'consolacao', name: 'Consolação' },
  { slug: 'freguesia-do-o', name: 'Freguesia do Ó' },
  { slug: 'higienopolis', name: 'Higienópolis' },
  { slug: 'ipiranga', name: 'Ipiranga' },
  { slug: 'itaim-bibi', name: 'Itaim Bibi' },
  { slug: 'jabaquara', name: 'Jabaquara' },
  { slug: 'jaguare', name: 'Jaguaré' },
  { slug: 'jardim-america', name: 'Jardim América' },
  { slug: 'jardim-analia-franco', name: 'Jardim Anália Franco' },
  { slug: 'jardim-avelino', name: 'Jardim Avelino' },
  { slug: 'jardim-brasil', name: 'Jardim Brasil' },
  { slug: 'jardim-europa', name: 'Jardim Europa' },
  { slug: 'jardim-iris', name: 'Jardim Iris' },
  { slug: 'jardim-marajoara', name: 'Jardim Marajoara' },
  { slug: 'jardim-paulista', name: 'Jardim Paulista' },
  { slug: 'jardim-paulistano', name: 'Jardim Paulistano' },
  { slug: 'lapa', name: 'Lapa' },
  { slug: 'liberdade', name: 'Liberdade' },
  { slug: 'mandaqui', name: 'Mandaqui' },
  { slug: 'moema', name: 'Moema' },
  { slug: 'mooca', name: 'Mooca' },
  { slug: 'pacaembu', name: 'Pacaembu' },
  { slug: 'parque-anhanguera', name: 'Parque Anhanguera' },
  { slug: 'parque-novo-mundo', name: 'Parque Novo Mundo' },
  { slug: 'perdizes', name: 'Perdizes' },
  { slug: 'pinheiros', name: 'Pinheiros' },
  { slug: 'piqueri', name: 'Piqueri' },
  { slug: 'planalto-paulista', name: 'Planalto Paulista' },
  { slug: 'sacoma', name: 'Sacomã' },
  { slug: 'santa-cecilia', name: 'Santa Cecília' },
  { slug: 'santana', name: 'Santana' },
  { slug: 'santo-amaro', name: 'Santo Amaro' },
  { slug: 'saude', name: 'Saúde' },
  { slug: 'sumare', name: 'Sumaré' },
  { slug: 'tatuape', name: 'Tatuapé' },
  { slug: 'tucuruvi', name: 'Tucuruvi' },
  { slug: 'vila-carrao', name: 'Vila Carrão' },
  { slug: 'vila-clementino', name: 'Vila Clementino' },
  { slug: 'vila-constancia', name: 'Vila Constância' },
  { slug: 'vila-ede', name: 'Vila Ede' },
  { slug: 'vila-formosa', name: 'Vila Formosa' },
  { slug: 'vila-guilherme', name: 'Vila Guilherme' },
  { slug: 'vila-gustavo', name: 'Vila Gustavo' },
  { slug: 'vila-leopoldina', name: 'Vila Leopoldina' },
  { slug: 'vila-madalena', name: 'Vila Madalena' },
  { slug: 'vila-maria', name: 'Vila Maria' },
  { slug: 'vila-mariana', name: 'Vila Mariana' },
  { slug: 'vila-mascote', name: 'Vila Mascote' },
  { slug: 'vila-mazzei', name: 'Vila Mazzei' },
  { slug: 'vila-nova-conceicao', name: 'Vila Nova Conceição' },
  { slug: 'vila-olimpia', name: 'Vila Olímpia' },
  { slug: 'vila-pompeia', name: 'Vila Pompeia' },
  { slug: 'vila-prudente', name: 'Vila Prudente' },
  { slug: 'vila-romana', name: 'Vila Romana' },
  { slug: 'vila-sabrina', name: 'Vila Sabrina' },
  { slug: 'vila-santa-clara', name: 'Vila Santa Clara' },
];

export type TransactionType = 'rent' | 'sale';

export function buildNeighborhoodUrl(neighborhood: Neighborhood, transaction: TransactionType): string {
  const action = transaction === 'rent' ? 'alugar' : 'comprar';
  return `https://www.quintoandar.com.br/${action}/imovel/sao-paulo-sp-brasil/bairro-${neighborhood.slug}`;
}
