name: Test
on:
  pull_request:
    branches:
      - main
      - master
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install deps
        run: npm ci

      - name: Run prisma codegen
        run: npm run db:codegen --workspace=@repo/db

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Start database
        run: docker compose up -d --wait

      - name: Syncpack
        run: npm run packages:check

      - name: Run migrations
        run: npm run migrate:deploy

      - name: Run tests
        run: npm run test
